### ISSUE TITLE
Refactor code to remove OODT dependencies

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-harvest-legacy#75]
### 💡 Description

The code is very old and prone to vulnerabilities. Let's refactor it out.

It is primarily used for crawler, metadata extraction and in-memory storage, which I think we can just create objects to do and/or use existing libraries to do it (e.g. validate has it's own crawler code)

**Comment by tloubrieu-jpl** [comment]
dependencies have been removed but need to be tested...

**Comment by tloubrieu-jpl** [comment]
@jordanpadams is fine tuning the dependencies to avoid the security issues.
